package com.foresightlabs.aether.data.telegram

import com.foresightlabs.aether.domain.text.LinkPreviewCard
import com.foresightlabs.aether.domain.text.LinkPreviewIntent
import org.drinkless.tdlib.TdApi

/**
 * The TDLib side of Composer link previews.
 *
 * Two translations, both of them small and both of them pure:
 *  - what `TdApi.LinkPreview` — Telegram's own answer for a link — means for
 *    the Composer;
 *  - what the Composer's intent means for `TdApi.LinkPreviewOptions` on the way
 *    back out through the ordinary send path.
 *
 * Nothing here fetches anything. The preview is generated by Telegram, through
 * `TdApi.GetLinkPreview`; no page is read and no site content is downloaded to
 * build it.
 */
object LinkPreviewSupport {

    /**
     * Telegram's preview, reduced to the fields the Composer shows.
     *
     * @param resolvePath a local path for the thumbnail file, when its bytes
     *   are already on disk. Passing a resolver that also *starts* a download is
     *   fine: the tiny embedded thumbnail carries the preview until they arrive.
     */
    fun cardOf(
        preview: TdApi.LinkPreview?,
        resolvePath: (TdApi.File?) -> String? = { null }
    ): LinkPreviewCard? {
        if (preview == null) return null
        val url = preview.url.orEmpty().ifBlank { preview.displayUrl.orEmpty() }
        if (url.isBlank()) return null
        val photo = photoOf(preview.type)
        val thumbnailFile = smallestFile(photo)
        return LinkPreviewCard(
            url = url,
            displayUrl = preview.displayUrl.orEmpty().ifBlank { url },
            siteName = preview.siteName.orEmpty(),
            title = preview.title.orEmpty(),
            description = preview.description?.text.orEmpty(),
            thumbnailPath = resolvePath(thumbnailFile),
            thumbnailBase64 = TelegramMappers.minithumbnailBase64(photo?.minithumbnail)
        )
    }

    /** The file id of the preview's thumbnail, or 0 when it has none. */
    fun thumbnailFileId(preview: TdApi.LinkPreview?): Int =
        smallestFile(photoOf(preview?.type))?.id ?: 0

    /**
     * The preview options one outgoing message carries.
     *
     * Null for the default case, so a message with no link — and a message whose
     * preview the user left alone — sends exactly the request it did before this
     * feature existed.
     */
    fun optionsFor(intent: LinkPreviewIntent): TdApi.LinkPreviewOptions? = when (intent) {
        LinkPreviewIntent.Default -> null
        LinkPreviewIntent.Disabled -> TdApi.LinkPreviewOptions(true, "", false, false, false)
        // The URL is named explicitly, so what sends is the preview the user
        // actually saw rather than whichever link Telegram would pick again.
        is LinkPreviewIntent.Show -> TdApi.LinkPreviewOptions(false, intent.url, false, false, false)
    }

    /**
     * The photo a preview type carries, across the kinds of link people paste.
     *
     * Types with no still image of their own return null, and the Composer then
     * shows a preview without a thumbnail rather than an empty frame.
     */
    private fun photoOf(type: TdApi.LinkPreviewType?): TdApi.Photo? = when (type) {
        is TdApi.LinkPreviewTypeArticle -> type.photo
        is TdApi.LinkPreviewTypePhoto -> type.photo
        is TdApi.LinkPreviewTypeApp -> type.photo
        is TdApi.LinkPreviewTypeVideo -> type.cover
        is TdApi.LinkPreviewTypeEmbeddedVideoPlayer -> type.thumbnail
        is TdApi.LinkPreviewTypeEmbeddedAnimationPlayer -> type.thumbnail
        is TdApi.LinkPreviewTypeEmbeddedAudioPlayer -> type.thumbnail
        is TdApi.LinkPreviewTypeAlbum -> type.media
            ?.asSequence()
            ?.filterIsInstance<TdApi.LinkPreviewAlbumMediaPhoto>()
            ?.firstOrNull()
            ?.photo
        else -> null
    }

    /** The smallest variant: this is a thumbnail, not the picture itself. */
    private fun smallestFile(photo: TdApi.Photo?): TdApi.File? = photo?.sizes
        ?.filterNotNull()
        ?.minByOrNull { it.width.toLong() * it.height.toLong() }
        ?.photo
}
