package com.foresightlabs.aether.domain.sharing

import androidx.compose.runtime.Immutable
import com.foresightlabs.aether.domain.text.ComposerLinks

/**
 * What kind of thing another application handed Aether.
 *
 * Deliberately coarse: Aether only needs to know which existing send path an
 * item belongs in. Anything that is not an image or a video is a file, because
 * that is exactly the distinction Telegram's own input types draw.
 */
enum class SharedAttachmentKind { IMAGE, VIDEO, FILE }

/**
 * One shared attachment, still as the URI the source application granted.
 *
 * [uri] is held as the string form of a `content://` URI and is never treated as
 * a filesystem path -- the bytes are read through the content resolver, and only
 * then does a real file exist for the Telegram send path. See
 * [com.foresightlabs.aether.data.sharing.SharedUriGateway].
 */
@Immutable
data class SharedAttachment(
    val uri: String,
    val kind: SharedAttachmentKind,
    val mimeType: String? = null,
    val name: String? = null
)

/**
 * Content that arrived through the Android Sharesheet, normalized.
 *
 * Two shapes, because Aether has two send paths to deliver into: text, and
 * attachments. A shared link is not a third shape -- it is [Text] whose [Text.link]
 * is set, and the preview for it is generated by Telegram through the Composer's
 * existing link-preview mechanism rather than by reading the page here.
 *
 * "Multiple" is [Attachments] with more than one item; the album send is what
 * makes that difference matter, not the model.
 */
@Immutable
sealed interface SharedContent {

    /** Shared text, which may be or contain a URL. */
    @Immutable
    data class Text(val text: String) : SharedContent {
        /** The URL Telegram would preview, or null when this is prose. */
        val link: String? get() = ComposerLinks.firstUrl(text)
    }

    /** One or more shared images, videos or files, with any text as their caption. */
    @Immutable
    data class Attachments(
        val items: List<SharedAttachment>,
        val caption: String = ""
    ) : SharedContent

    /** A short line describing the share, in Aether's own words. */
    val summary: String
        get() = when (this) {
            is Text -> link ?: text
            is Attachments -> {
                val label = when {
                    items.size > 1 -> "${items.size} items"
                    items.firstOrNull()?.kind == SharedAttachmentKind.IMAGE -> "Photo"
                    items.firstOrNull()?.kind == SharedAttachmentKind.VIDEO -> "Video"
                    else -> items.firstOrNull()?.name ?: "File"
                }
                if (caption.isBlank()) label else "$label · $caption"
            }
        }

    /** Every attachment this share carries; empty for shared text. */
    val attachments: List<SharedAttachment>
        get() = (this as? Attachments)?.items.orEmpty()

    /** Whether this share needs the album path rather than a single send. */
    val isMultiple: Boolean get() = attachments.size > 1
}

/**
 * Who a share may be sent to.
 *
 * The same answer Aether gives everywhere else about who can be written to,
 * asked once here so recipient selection cannot drift from it: a personal
 * conversation the account may send text in. Groups, channels, bots, forums,
 * Saved Messages and Telegram's own service account are not offered -- a share
 * addressed to them is not something Aether can deliver.
 */
object ShareRecipients {
    fun eligible(
        chats: List<com.foresightlabs.aether.domain.model.Chat>
    ): List<com.foresightlabs.aether.domain.model.Chat> =
        chats.filter { it.canSendText && it.isPersonalChat }
}
