package com.foresightlabs.aether.ui.auth

data class CountryDial(
    val name: String,
    val iso: String,
    val dial: String,
    val flag: String
)

object CountryDials {
    val list: List<CountryDial> = listOf(
        CountryDial("United States", "US", "1", "🇺🇸"),
        CountryDial("United Kingdom", "GB", "44", "🇬🇧"),
        CountryDial("India", "IN", "91", "🇮🇳"),
        CountryDial("Germany", "DE", "49", "🇩🇪"),
        CountryDial("France", "FR", "33", "🇫🇷"),
        CountryDial("Italy", "IT", "39", "🇮🇹"),
        CountryDial("Spain", "ES", "34", "🇪🇸"),
        CountryDial("Brazil", "BR", "55", "🇧🇷"),
        CountryDial("Canada", "CA", "1", "🇨🇦"),
        CountryDial("Australia", "AU", "61", "🇦🇺"),
        CountryDial("Japan", "JP", "81", "🇯🇵"),
        CountryDial("South Korea", "KR", "82", "🇰🇷"),
        CountryDial("China", "CN", "86", "🇨🇳"),
        CountryDial("Russia", "RU", "7", "🇷🇺"),
        CountryDial("Ukraine", "UA", "380", "🇺🇦"),
        CountryDial("Poland", "PL", "48", "🇵🇱"),
        CountryDial("Netherlands", "NL", "31", "🇳🇱"),
        CountryDial("Turkey", "TR", "90", "🇹🇷"),
        CountryDial("Indonesia", "ID", "62", "🇮🇩"),
        CountryDial("Pakistan", "PK", "92", "🇵🇰"),
        CountryDial("Bangladesh", "BD", "880", "🇧🇩"),
        CountryDial("Nigeria", "NG", "234", "🇳🇬"),
        CountryDial("Mexico", "MX", "52", "🇲🇽"),
        CountryDial("Argentina", "AR", "54", "🇦🇷"),
        CountryDial("South Africa", "ZA", "27", "🇿🇦"),
        CountryDial("United Arab Emirates", "AE", "971", "🇦🇪"),
        CountryDial("Saudi Arabia", "SA", "966", "🇸🇦"),
        CountryDial("Israel", "IL", "972", "🇮🇱"),
        CountryDial("Sweden", "SE", "46", "🇸🇪"),
        CountryDial("Norway", "NO", "47", "🇳🇴"),
        CountryDial("Denmark", "DK", "45", "🇩🇰"),
        CountryDial("Finland", "FI", "358", "🇫🇮"),
        CountryDial("Switzerland", "CH", "41", "🇨🇭"),
        CountryDial("Austria", "AT", "43", "🇦🇹"),
        CountryDial("Belgium", "BE", "32", "🇧🇪"),
        CountryDial("Portugal", "PT", "351", "🇵🇹"),
        CountryDial("Greece", "GR", "30", "🇬🇷"),
        CountryDial("Czechia", "CZ", "420", "🇨🇿"),
        CountryDial("Romania", "RO", "40", "🇷🇴"),
        CountryDial("Hungary", "HU", "36", "🇭🇺"),
        CountryDial("Ireland", "IE", "353", "🇮🇪"),
        CountryDial("New Zealand", "NZ", "64", "🇳🇿"),
        CountryDial("Singapore", "SG", "65", "🇸🇬"),
        CountryDial("Malaysia", "MY", "60", "🇲🇾"),
        CountryDial("Thailand", "TH", "66", "🇹🇭"),
        CountryDial("Vietnam", "VN", "84", "🇻🇳"),
        CountryDial("Philippines", "PH", "63", "🇵🇭"),
        CountryDial("Egypt", "EG", "20", "🇪🇬"),
        CountryDial("Kenya", "KE", "254", "🇰🇪"),
        CountryDial("Colombia", "CO", "57", "🇨🇴"),
        CountryDial("Chile", "CL", "56", "🇨🇱")
    )
}
