package com.foresightlabs.aether.domain.daily

/**
 * The Aether Daily corpus.
 *
 * Original Foresight Labs micro-lines written for Aether. Nothing here is scraped,
 * quoted or attributed to anyone else, and no network call is involved — the whole
 * collection ships with the app so Aether Daily works offline forever.
 *
 * Categories exist to keep the collection varied in tone rather than to switch the
 * line mid-day; see [AetherDaily] for why selection is seeded by date alone.
 */
enum class DailyCategory {
    MORNING,
    DAY,
    EVENING,
    NIGHT,
    RAIN,
    GENERAL
}

data class DailyLine(val text: String, val category: DailyCategory)

object AetherDailyLines {

    private val morning = listOf(
        "The day hasn't decided anything yet.",
        "Somebody woke up hoping to hear from you.",
        "Start with the message you keep postponing.",
        "Morning is a good time to be uncomplicated.",
        "First light, first word, first small kindness.",
        "You don't have to be ready to begin.",
        "Say good morning to someone who wouldn't expect it.",
        "The inbox can wait. The person can't, quite.",
        "Today gets to be different than yesterday.",
        "Reply early. It reads as care.",
        "A short answer beats a perfect one you never send.",
        "There's someone whose morning you could improve in nine words.",
        "Wake slowly. Answer warmly.",
        "You are allowed a gentle start.",
        "Nothing has gone wrong yet. Enjoy that part.",
        "Send the thought before the day crowds it out.",
        "The best hours are usually the unscheduled ones.",
        "Check in on the quiet one first.",
        "Small talk is still talk.",
        "Someone is rereading your last message this morning.",
        "Begin with the easiest good thing.",
        "The list will shrink. The people won't.",
        "You can be behind on everything and still be kind.",
        "Ask how they slept. Mean it.",
        "The morning is patient with beginners.",
        "One honest sentence is a whole conversation started.",
        "Coffee, then courage, then the message.",
        "Whatever you carried into sleep can be set down now.",
        "Today's version of you gets a fresh read.",
        "The first message sets the temperature.",
        "Nobody remembers the punctuality. They remember the tone.",
        "Let the first thing you send be warm.",
        "Some mornings the bravest act is answering.",
        "You are further along than you feel.",
        "Say the name of someone you miss. Then message them.",
        "New day, same people worth keeping.",
        "The hardest message gets easier before nine.",
        "Give the morning something worth remembering.",
        "You woke up with a working heart and a full signal.",
        "Be the reason a phone lights up kindly.",
        "There is no backlog on affection.",
        "Sunrise doesn't ask whether you're prepared.",
        "Answer one person properly instead of five carelessly.",
        "It's early. There's room.",
        "The day is unwritten and you have the pen."
    )

    private val day = listOf(
        "Busy is not the same as unreachable.",
        "Two minutes is enough to change someone's afternoon.",
        "The urgent thing is rarely the important person.",
        "You can pause mid-task to be human.",
        "Half a conversation now beats a whole one never.",
        "Someone assumed you were too busy. Prove them wrong.",
        "Between the meetings there is a whole life.",
        "Send it now. Polish it never.",
        "Your attention is the actual gift.",
        "The work will still be there. So will they, if you're lucky.",
        "Answer the message you've been avoiding. It's smaller than you think.",
        "Midday is a fine time to be generous.",
        "Nobody has ever regretted a kind interruption.",
        "You're allowed to be reachable and unbothered.",
        "The group chat isn't the same without you.",
        "Reply badly rather than not at all.",
        "Take the call. Or don't, but say why.",
        "There's a person behind every unread badge.",
        "Progress is quieter than it looks from inside.",
        "You have already done more than you've credited yourself for.",
        "Let someone know you thought of them today.",
        "Efficiency is not a personality.",
        "A short voice note carries more than a long paragraph.",
        "The afternoon slump is a good moment for a hello.",
        "Delegate the task. Keep the friendship.",
        "It's fine to be slow today.",
        "One good conversation redeems an ordinary day.",
        "Someone is waiting for permission to message you first.",
        "Being present is a skill and you can practise it now.",
        "The best replies are the unhurried ones.",
        "Not every notification deserves you. Some do.",
        "Check on the friend who always seems fine.",
        "You can close the laptop and still be responsible.",
        "Say thank you before the moment goes stale.",
        "Distance is only a problem if nobody writes.",
        "There is time. There is usually time.",
        "A message costs nothing and lands like something.",
        "Interrupt yourself to be kind.",
        "The middle of the day is the middle of nothing. Keep going.",
        "Answer as yourself, not as your job title."
    )

    private val evening = listOf(
        "The day is closing. Who did you forget to tell?",
        "Evening is honest in a way morning isn't.",
        "Say the thing worth remembering.",
        "Good conversations make distance feel smaller.",
        "Whatever went badly is smaller after dark.",
        "There's still time to send it.",
        "Somebody is probably thinking of you too.",
        "The last message of the day should be a warm one.",
        "Let the day end on a decent sentence.",
        "Call instead of typing, just once.",
        "Nothing unsaid gets lighter overnight.",
        "You survived the whole thing. That counts.",
        "The evening forgives a slow reply.",
        "Ask someone how it actually went.",
        "Sunset is a reminder that endings can be beautiful.",
        "Put the day down gently.",
        "The quiet hours are for the real conversations.",
        "You don't owe anyone a summary of your day. But it's nice to share.",
        "Tell someone the good part before you forget it.",
        "Evening light makes everyone look forgiven.",
        "There's a message you'll regret not sending tonight.",
        "The people who wait up for you are the point.",
        "Say goodnight like you mean it.",
        "Let the last hour be unproductive on purpose.",
        "What you didn't finish will keep.",
        "A quiet hello can change a day, even a late one.",
        "The day gave you something. Name it.",
        "Talk to someone who knew you before all this.",
        "Evenings are for the friends you don't have to explain yourself to.",
        "Close the loops that are actually people.",
        "You can end the day kinder than you started it.",
        "Reach out before the tiredness decides for you.",
        "Send the photo you took and forgot about.",
        "Some conversations only work after dark.",
        "The best evenings are the unplanned ones.",
        "Ask about the thing they mentioned last week.",
        "Let someone know their message mattered.",
        "The day is over. The friendship isn't.",
        "There's no such thing as a small check-in.",
        "Say it while the day still holds it."
    )

    private val night = listOf(
        "Not every late thought needs to stay unsent.",
        "The night makes small things enormous. Don't trust it entirely.",
        "Someone else is awake too.",
        "Whatever you're turning over will look different by morning.",
        "Late messages are honest messages.",
        "You are allowed to rest before you have finished.",
        "The dark hours are generous with old memories.",
        "It can wait until tomorrow. Most of it can.",
        "If you're awake and thinking of them, tell them tomorrow.",
        "Nothing needs solving at this hour.",
        "The quiet is not empty. It's just quiet.",
        "Sleep is a reasonable response to almost everything.",
        "Tomorrow gets a clean signal.",
        "The people who matter will still be there at nine.",
        "Midnight is a poor advisor and a good listener.",
        "Put the phone down kindly.",
        "You've done enough for one rotation of the planet.",
        "Late-night courage is real courage. Use it carefully.",
        "The message will read differently in daylight. That's fine.",
        "Rest is not a reward. It's maintenance.",
        "Some things are better said when nobody is rushing.",
        "The night doesn't need your productivity.",
        "You can close every app and nothing will break.",
        "Whoever you're missing right now — that's information.",
        "Long after the noise, the same few names remain.",
        "Sleep on it. Then send it.",
        "The world got through today without your supervision.",
        "There's nothing left to optimise tonight.",
        "Tomorrow you'll have more patience. Save it for someone good.",
        "Silence at this hour is a kind of company.",
        "Let the unread stay unread until morning.",
        "The last light on the street is not a deadline.",
        "You're not behind. You're just tired.",
        "Everything urgent looks smaller at 2am and always was.",
        "Say goodnight and mean the good part.",
        "The night keeps what you tell it.",
        "There will be another day, and people in it.",
        "Nothing you decide now has to be permanent.",
        "Stop reading. Start sleeping.",
        "It's late. Be gentle with the version of you that's still awake."
    )

    private val rain = listOf(
        "Rain is a good excuse to stay in and catch up with someone.",
        "The weather cleared your schedule. Use it on a person.",
        "Grey outside, warm in here.",
        "Rain makes the indoors feel deliberate.",
        "Nobody expects much of you in this weather.",
        "The best conversations happen when going out isn't an option.",
        "Let the rain do the talking for a while.",
        "Weather like this is made for long replies.",
        "Everything sounds softer through rain.",
        "A storm is just the sky clearing its throat.",
        "Stay in. Message someone far away.",
        "Rain slows the whole city down. Match it.",
        "There's no rush in this kind of weather.",
        "Grey days are honest days.",
        "The window is doing something worth watching.",
        "Rain gives you permission to be unhurried.",
        "Wet streets, warm signal.",
        "This is weather for old friends and long messages.",
        "Nothing to do but talk. Not the worst outcome.",
        "Let the rain reschedule you.",
        "Storms end. So do most difficult conversations.",
        "The forecast said stay close to someone.",
        "Rain is the sound of the world taking a break.",
        "Even the sky needs to let go sometimes.",
        "Weather this dramatic deserves an audience. Tell someone."
    )

    private val general = listOf(
        "Say the thing you've been rehearsing.",
        "Most people want to hear from you more than you assume.",
        "Distance is a logistics problem, not a feelings problem.",
        "A conversation is the smallest unit of belonging.",
        "You are somebody's favourite notification.",
        "Being known takes repetition, not intensity.",
        "The friendship survives the gap if someone writes.",
        "There's no expiry date on a good apology.",
        "Ask the question you're afraid of the answer to.",
        "Listening well is rarer than talking well.",
        "You can restart any conversation with one sentence.",
        "The people who check in are doing something quietly heroic.",
        "Nobody has ever felt worse for being thought of.",
        "Send the message. Reread it never.",
        "Presence beats eloquence.",
        "Old friends are a form of memory you don't have to maintain alone.",
        "The right person makes a small update feel worth sending.",
        "You are not too much for the people who chose you.",
        "Some silences are comfortable. Check which kind yours is.",
        "Say what you noticed. It's more flattering than a compliment.",
        "Reaching out first is not losing.",
        "The message you almost sent is usually the honest one.",
        "Everyone is improvising. Some just have better lighting.",
        "A friendship is a series of returns.",
        "You get to decide who gets your attention today.",
        "The best relationships are low-maintenance and high-priority.",
        "Assume warmth. It's right more often than not.",
        "It's never too late to be in touch again.",
        "You don't need an occasion.",
        "Being reachable is a kind of generosity.",
        "Tell people what they mean while it's still easy.",
        "The unread count is not a moral failing.",
        "Some people are worth being interrupted for.",
        "Say yes to the plan you keep postponing.",
        "Honesty is cheaper than maintenance.",
        "The conversation you avoid becomes the conversation you dread.",
        "Nobody outgrows being asked how they are.",
        "A friendship without updates is just a memory.",
        "You can be private and still be close.",
        "Sending something first is a small act of faith.",
        "The people who make you feel ordinary in a good way — keep them.",
        "Not every message needs a purpose.",
        "You can love people badly and still love them.",
        "Say the specific thing, not the general one.",
        "Being remembered is mostly about remembering.",
        "There is a version of this conversation that goes well.",
        "You have more allies than you're counting.",
        "Warmth is a decision you can make repeatedly.",
        "The good ones don't keep score, but they do notice.",
        "Every long friendship survived a period of silence.",
        "Tell them the story while it's still funny.",
        "Small consistent contact beats grand rare gestures.",
        "You don't have to be interesting to be wanted around.",
        "A message is a door held open.",
        "Some people only need to know you're still there.",
        "Curiosity is the most underrated form of affection.",
        "You are allowed to want to be checked on.",
        "Nobody minds a slightly awkward reconnection.",
        "The distance between you is mostly unsent messages.",
        "Say thank you specifically enough that it lands.",
        "The best conversations have no agenda.",
        "It is normal to miss people you see often.",
        "Be the friend who follows up.",
        "One person paying attention changes the whole day.",
        "Ask about the small thing. That's where people live.",
        "You can be tired and still be a good friend.",
        "The relationship is not fragile. Test it gently.",
        "Everyone is a little lonelier than they let on.",
        "Send the meme. It counts.",
        "A short message is not a lesser message.",
        "You'll never regret checking in.",
        "The hardest part is the first word.",
        "People forgive lateness. They notice absence.",
        "You are not behind on anything that matters.",
        "It's okay to need people out loud.",
        "The best friendships are unremarkable most days.",
        "Say it plainly. Plain lands harder.",
        "There is no correct frequency for caring.",
        "Somebody saved a message you sent without thinking.",
        "Reconnection is easier than you're imagining.",
        "The people who knew you before are worth the effort.",
        "Presence is mostly showing up in text.",
        "You can change the mood of a room from far away.",
        "Not all closeness is loud.",
        "It's fine to say you don't know what to say.",
        "The best answer to 'how are you' is a real one.",
        "Some conversations only need to be continued, not concluded.",
        "Care is a practice, not a feeling.",
        "You are somebody's reliable person. Act like it, gently.",
        "Ask twice. The second answer is usually true.",
        "Nobody has ever complained about being sent a photo of something small and good.",
        "The friendship is not over. It's just quiet.",
        "You can start again in the middle.",
        "The right message at the wrong time still helps.",
        "Talk to people while they're still ordinary to you.",
        "There is always something to say to someone you like.",
        "The best relationships forgive bad grammar.",
        "Being easy to talk to is a real accomplishment.",
        "A group chat is a small country. Visit it.",
        "You matter to people who never say so.",
        "The version of you they know is kinder than the one you know.",
        "Send it before you talk yourself out of it.",
        "Some people are home. Message home.",
        "Nothing is as final as it feels.",
        "You're allowed to want more from a friendship.",
        "The check-in you almost skipped is the one they needed.",
        "Being consistent is more impressive than being impressive.",
        "There is no wrong hour to say you were thinking of them.",
        "Ordinary days make the best shared memories.",
        "Keep the people who make you less performative.",
        "You can be honest without being heavy.",
        "The conversation is more forgiving than your imagination.",
        "Everyone likes being someone's first thought.",
        "Say the compliment before it becomes a eulogy.",
        "It's a good day to be reachable.",
        "The message you'd want to receive — send that one.",
        "Nobody is too busy for thirty seconds of warmth.",
        "You don't have to fix anything to be useful.",
        "Sitting with someone is a full contribution.",
        "The friendship survives disagreement more easily than distance.",
        "Say the awkward true thing.",
        "You're better at this than you think.",
        "Some people just need to hear their name.",
        "Every relationship needs someone willing to go first.",
        "A little effort looks like a lot from the outside.",
        "Somebody's day improves the moment you appear.",
        "You can be far away and still be close.",
        "Not every silence needs interpreting.",
        "Reach for the person, not the platform.",
        "The point was never the messages. It was the person.",
        "There's someone you should tell you're proud of.",
        "You are permitted to take up space in someone's day.",
        "The best conversations end with 'talk soon' and mean it.",
        "A question is a gift.",
        "Say what you'd want said back.",
        "Being warm costs nothing and compounds.",
        "You will not always have this much time.",
        "The right people make replying feel easy.",
        "It's not needy to want to be wanted.",
        "Send the update nobody asked for.",
        "Keep the friendships that survive honesty.",
        "There is nothing embarrassing about caring visibly.",
        "The distance closes from either end.",
        "Say the good thing out loud, in writing, today.",
        "Attention is the rarest thing you can offer.",
        "You are not an inconvenience.",
        "The message doesn't have to be good, only sent.",
        "Somebody kept the conversation open in case you came back.",
        "Reconnect without a preamble. Just start.",
        "A long friendship is mostly forgiveness and timing.",
        "Say it now while it's still true.",
        "The best thing you can do today might take one minute.",
        "Nobody's closeness is automatic. It's chosen, repeatedly.",
        "You have people. Use them, kindly.",
        "Be interested before you're interesting.",
        "Some doors only need a knock.",
        "The friendship you're worried about is probably fine.",
        "Send love in whatever format you have.",
        "The conversation is worth more than the conclusion.",
        "You are already someone's good memory.",
        "There's a lot of life inside a short exchange.",
        "Being known is worth the awkwardness of being seen.",
        "The people who stay are the ones you told the truth to.",
        "Say hello to someone you've been circling.",
        "Nothing improves by being left unsaid.",
        "A relationship is just a conversation that kept going.",
        "You're allowed to reach out without a reason.",
        "The world is smaller than the silence suggests.",
        "Somebody would take your call right now.",
        "The friendship deserves better than good intentions.",
        "Say the true thing gently and completely.",
        "You don't need to be at your best to be in touch.",
        "Every unanswered message is a small door left open.",
        "The people worth knowing are patient with slow replies.",
        "Warmth is not a limited resource.",
        "There is someone you could make laugh in the next minute.",
        "A conversation is the only thing that gets better the more you spend it.",
        "You're the person somebody hopes messages first.",
        "Be specific. Vague warmth doesn't land.",
        "The best gift is being remembered accurately.",
        "It's a small planet and you have signal.",
        "Somebody needs the exact thing you almost didn't say.",
        "Care loudly enough to be heard.",
        "The friendship is not a debt. Stop keeping accounts.",
        "You can always begin with 'this reminded me of you'.",
        "There is a conversation waiting that you'd enjoy.",
        "Send it. The worst case is a short reply.",
        "You have never regretted being warm first.",
        "Nobody keeps a tally of who wrote last except the anxious.",
        "The person you're avoiding is probably not avoiding you.",
        "Being liked is mostly a side effect of being interested.",
        "A friendship can survive almost anything except being ignored.",
        "You can apologise without knowing exactly what went wrong.",
        "Half the distance in any relationship is imagined.",
        "Say the sentence that costs you something.",
        "Familiarity is not the opposite of affection.",
        "There is no threshold of importance a message must clear.",
        "The people who ask follow-up questions are the ones to keep.",
        "You are allowed to be the one who cares more this week.",
        "Every strong friendship has an unglamorous maintenance schedule.",
        "Reaching out badly beats reaching out never.",
        "Talk about the thing, not around it.",
        "The best listeners are not silent, they are curious.",
        "You do not have to earn the right to be missed.",
        "Some people improve every room and never notice.",
        "A shared joke is a small private country.",
        "It is easier to stay close than to get close again. Do the easy thing.",
        "Nobody is waiting for you to be impressive.",
        "The right person hears the tone, not the typo.",
        "Tell them what you almost didn't say.",
        "Warmth given early is worth more than warmth given perfectly.",
        "Every friendship is a series of small unrepaid kindnesses.",
        "You are more forgiven than you think.",
        "Curiosity outlasts charm.",
        "Ask what they're working on. Then actually listen.",
        "Reconnecting has no correct opening line.",
        "The best relationships are boring in the best way.",
        "You can be the reason someone stops doubting themselves.",
        "There is nothing weak about wanting to be included.",
        "Say the good thing before you find a reason not to.",
        "A friend who checks in twice is not needy, they are rare.",
        "Being consistent is the whole trick.",
        "You do not need to resolve the feeling to name it.",
        "The version of the conversation in your head is worse than the real one.",
        "Some people are worth changing your plans for.",
        "It costs nothing to be the first to soften.",
        "A relationship is what survives the inconvenient parts.",
        "You will remember who answered.",
        "Attention is affection with the volume down.",
        "The message that feels too small is usually the right size.",
        "Nobody has ever been annoyed by being told they're missed.",
        "You can hold two people's truths at once.",
        "Say it without a joke attached, just once.",
        "The friendship does not need a reason to continue.",
        "Everyone has a person they're afraid to message first.",
        "There is more room in people than you assume.",
        "Being easy to reach is underrated generosity.",
        "You can be honest and still be kind about it.",
        "The best thing about people is that they keep changing.",
        "Ask about the part they skipped over.",
        "A short message sent today outranks a long one imagined.",
        "You are somebody's proof that people can be decent.",
        "Talking is how two people stay the same size to each other.",
        "It is not too late to be the friend you meant to be.",
        "The silence is usually about them, not you.",
        "Give people the version of you that you'd want back.",
        "Some conversations are worth having badly.",
        "The people who stay are rarely the loudest.",
        "You can be tired of everything and still glad they wrote.",
        "Care shows up as follow-up.",
        "There is a person who would be delighted to hear from you.",
        "Say what you noticed, not what you assumed.",
        "The best friendships have no maintenance manual and work anyway.",
        "You are allowed to want a reply.",
        "Every honest conversation makes the next one easier.",
        "Not knowing what to say is not a reason to say nothing.",
        "The people worth keeping make you feel less strange.",
        "A question asked twice is a kindness.",
        "You can restart anything with 'hey, been thinking about you'.",
        "It is normal to feel far away from people you love.",
        "The distance is made of days, not decisions.",
        "Somebody is hoping you're the one who breaks the silence.",
        "Warmth is a habit before it is a feeling.",
        "You do not have to be doing well to be in touch.",
        "The best conversations leave both people slightly changed.",
        "Say the thing that would embarrass you slightly.",
        "There is no version of caring that is too much for the right person.",
        "A friendship is a promise nobody wrote down.",
        "You can be someone's steadiest thing without trying hard.",
        "The reply you're dreading is usually one line long.",
        "Being remembered is the whole reward.",
        "Ask the question you'd want asked.",
        "Some people make you more yourself. Keep them close.",
        "You are not required to be interesting to be loved.",
        "Every relationship needs a person willing to be awkward.",
        "The conversation is a place, not a task.",
        "Tell them the small thing. The small things are the thing.",
        "Nobody outgrows wanting to be chosen.",
        "You can be honest about needing people.",
        "The best gift is undivided attention, briefly.",
        "It is easier to be kind than to explain why you weren't.",
        "Say it while it's still a feeling and not a memory.",
        "The people who know you are worth the effort of being known.",
        "A little warmth aimed precisely beats a lot aimed vaguely.",
        "You can end a hard conversation without winning it.",
        "There is always more time than you fear and less than you assume.",
        "Being reachable is a choice you make repeatedly.",
        "Somebody's opinion of themselves improves when you answer.",
        "The friendship is not a performance.",
        "Say what you'd regret leaving unsaid.",
        "You do not owe anyone constant availability, only honesty.",
        "The best people make being wrong survivable.",
        "Ask, then wait longer than feels comfortable.",
        "A conversation is the cheapest thing that changes everything.",
        "You can love someone and still find them difficult.",
        "The message costs a minute and buys a week.",
        "Nobody is as put together as their replies suggest.",
        "Say the ordinary thing. Ordinary is the point.",
        "There is someone whose day you are a fixed part of.",
        "Being interested is a skill, and it is learnable.",
        "You do not have to fix people to be good to them.",
        "The friendship you keep postponing is the one to pick up.",
        "Warmth is the only thing that grows when you spend it.",
        "Say more than 'you too'.",
        "Some people deserve a real answer, not a fast one.",
        "You are allowed to take up space in a conversation.",
        "The best relationships survive being unimpressive.",
        "Ask how it really went, and mean the 'really'.",
        "A message sent in doubt is still a message sent.",
        "There is nothing embarrassing about missing people.",
        "You can be the reason someone feels normal today.",
        "The good conversations have no summary.",
        "Say the true thing before the polite one.",
        "Nobody has ever been diminished by being generous first.",
        "The friendship is older than whatever went wrong.",
        "Being known well is worth being seen badly sometimes.",
        "You can start again without an explanation.",
        "The people who make time are telling you something.",
        "Ask about the thing they're proud of.",
        "A short honest reply outranks a long careful one.",
        "There is a conversation that would make your week. Start it.",
        "You are somebody's easiest person to talk to.",
        "Say the compliment specifically enough to be believed.",
        "The best friendships are mostly logistics and loyalty.",
        "Nobody regrets the time they spent on people.",
        "You can be the one who remembers.",
        "The distance closes one message at a time.",
        "Say something that only you would notice.",
        "Being present is mostly being unhurried.",
        "There is no correct amount of caring. Only honest amounts.",
        "You can want to be closer and say so.",
        "The friendship survives your worst week.",
        "Ask them to tell you the whole thing.",
        "A kind message is never wasted, even unanswered.",
        "Some people are a place you can put things down.",
        "You do not need a milestone to reach out.",
        "The best replies are specific, not clever.",
        "Nobody minds being thought of on an ordinary day.",
        "Say the thing that makes you slightly more visible.",
        "The people who last are the ones who came back.",
        "You can be quiet and still be close.",
        "Ask, listen, then ask again.",
        "A relationship is a habit two people agree to keep.",
        "There is more affection available to you than you're using.",
        "Say what you're grateful for while it's still specific.",
        "The friendship does not require a good reason.",
        "You are the person someone hopes picks up.",
        "Being warm is not the same as being available. Choose both when you can.",
        "The best conversations start with something unimportant.",
        "Nobody keeps score of who cared more. Almost nobody.",
        "You can say 'I don't know how to say this' and then say it.",
        "The people you think of are the message list.",
        "Say it plainly and let it land.",
        "There is nothing to prove in a good conversation.",
        "You can be far from someone and still be with them.",
        "Ask the second question. That's where it lives.",
        "A friendship is measured in returns, not intensity.",
        "Nobody is too far away to be told they matter.",
        "You are allowed to start the conversation you want to have.",
        "The best thing you can give is your full, brief attention.",
        "Say it now. Now is when it's true.",
        "The people who make you laugh deserve to know it.",
        "You can be a good friend badly and it still counts.",
        "There is someone you could make feel less alone in one line.",
        "Being generous with attention costs nothing and changes people.",
        "Say the thing you'd want to hear back."
    )

    /** The whole collection, contextual lines included. */
    val all: List<DailyLine> = buildList {
        general.forEach { add(DailyLine(it, DailyCategory.GENERAL)) }
        morning.forEach { add(DailyLine(it, DailyCategory.MORNING)) }
        day.forEach { add(DailyLine(it, DailyCategory.DAY)) }
        evening.forEach { add(DailyLine(it, DailyCategory.EVENING)) }
        night.forEach { add(DailyLine(it, DailyCategory.NIGHT)) }
        rain.forEach { add(DailyLine(it, DailyCategory.RAIN)) }
    }

    /**
     * The pool Aether Daily draws from.
     *
     * Only hour-neutral lines are eligible. A line is chosen once per local date and
     * must stay correct from midnight to midnight, so a line that asserts the reader's
     * time of day ("Say goodnight like you mean it") would contradict itself for most
     * of the day it was chosen for. The contextual lines stay in [all] for a future
     * time-aware surface, where asserting the hour is the point.
     */
    val dailyPool: List<DailyLine> =
        all.filter { it.category == DailyCategory.GENERAL }
}
